Repository AstarNetwork/Astar, pull requests merged in 2024-01, with the labels that each got.

#1116 dApps Staking v2 - claimStakerFor
  Cargo.lock
  pallets/dapps-staking/Cargo.toml
  pallets/dapps-staking/src/pallet/mod.rs
  pallets/dapps-staking/src/tests.rs
Labels: runtime

#1072 tests: fix typos
  tests/integration/src/unified_accounts.rs
  tests/integration/src/xvm.rs
  tests/xcm-simulator/src/mocks/parachain.rs
Labels: Stale, other

#1090 fix: typo fixes and grammar
  rpc-tests/README.md
Labels: documentation, other

#1119 feat: update precompile weight
  precompiles/assets-erc20/src/lib.rs
Labels: runtime

#1120 dApp Staking v3 - Legacy Ledger Support
  pallets/dapp-staking-v3/src/lib.rs
  pallets/dapp-staking-v3/src/test/tests.rs
Labels: runtime

#1121 dApp staking v3 precompile docs
  precompiles/dapp-staking-v3/DappsStakingV1.sol
  precompiles/dapp-staking-v3/DappsStakingV2.sol
  precompiles/dapp-staking-v3/DappsStakingV3.sol
  precompiles/dapp-staking-v3/README.md
Labels: documentation, runtime

#1123 dApp Staking v3 - Rewards As Tree
  pallets/dapp-staking-v3/src/lib.rs
  pallets/dapp-staking-v3/src/migrations.rs
  pallets/dapp-staking-v3/src/test/testing_utils.rs
  pallets/dapp-staking-v3/src/test/tests.rs
  pallets/dapp-staking-v3/src/test/tests_types.rs
  pallets/dapp-staking-v3/src/types.rs
  runtime/shibuya/src/lib.rs
Labels: shibuya, runtime

#1126 Expanded DappStakingApi
  Cargo.lock
  pallets/dapp-staking-v3/rpc/runtime-api/Cargo.toml
  pallets/dapp-staking-v3/rpc/runtime-api/src/lib.rs
  pallets/dapp-staking-v3/src/benchmarking/mod.rs
  pallets/dapp-staking-v3/src/lib.rs
  pallets/dapp-staking-v3/src/test/tests.rs
  runtime/local/src/lib.rs
  runtime/shibuya/src/lib.rs
Labels: shibuya, runtime

#1128 dApp Staking v3 - improvements & fixes
  pallets/dapp-staking-v3/src/lib.rs
  pallets/dapp-staking-v3/src/test/testing_utils.rs
  pallets/dapp-staking-v3/src/test/tests.rs
  pallets/dapp-staking-v3/src/test/tests_types.rs
  pallets/dapp-staking-v3/src/types.rs
  pallets/inflation/src/lib.rs
  pallets/inflation/src/tests.rs
  precompiles/dapp-staking-v3/src/test/mod.rs
  precompiles/dapp-staking-v3/src/test/tests_v1.rs
  precompiles/dapp-staking-v3/src/test/tests_v2.rs
  precompiles/dapp-staking-v3/src/test/tests_v3.rs
Labels: runtime

#1135 dApp Staking v3 - Unbond During Decommission
  pallets/dapps-staking/src/pallet/mod.rs
  pallets/dapps-staking/src/tests.rs
Labels: runtime

#1136 dApp Staking v3 - Incorrect Loyalty Status Fix
  pallets/dapp-staking-v3/src/test/testing_utils.rs
  pallets/dapp-staking-v3/src/test/tests_types.rs
  pallets/dapp-staking-v3/src/types.rs
Labels: runtime

#1134 dApp staking v3 - Cycle Alignment
  Cargo.lock
  chain-extensions/pallet-assets/Cargo.toml
  chain-extensions/pallet-assets/src/mock.rs
  pallets/dapp-staking-migration/src/mock.rs
  pallets/dapp-staking-v3/rpc/runtime-api/Cargo.toml
  pallets/dapp-staking-v3/rpc/runtime-api/src/lib.rs
  pallets/dapp-staking-v3/src/lib.rs
  pallets/dapp-staking-v3/src/test/mock.rs
  pallets/dapp-staking-v3/src/test/testing_utils.rs
  pallets/dapp-staking-v3/src/test/tests.rs
  pallets/dapp-staking-v3/src/test/tests_types.rs
  pallets/dapp-staking-v3/src/types.rs
  pallets/dapp-staking-v3/src/weights.rs
  pallets/inflation/src/benchmarking.rs
  pallets/inflation/src/lib.rs
  pallets/inflation/src/mock.rs
  pallets/inflation/src/tests.rs
  pallets/inflation/src/weights.rs
  pallets/static-price-provider/src/lib.rs
  precompiles/dapp-staking-v3/src/test/mock.rs
  precompiles/dapp-staking-v3/src/test/tests_v2.rs
  precompiles/dapp-staking-v3/src/test/tests_v3.rs
  primitives/src/dapp_staking.rs
  runtime/local/src/lib.rs
  runtime/shibuya/src/lib.rs
  runtime/shibuya/src/weights/pallet_dapp_staking_v3.rs
  runtime/shibuya/src/weights/pallet_inflation.rs
  tests/integration/Cargo.toml
  tests/integration/src/dapp_staking_v3.rs
  tests/integration/src/lib.rs
  tests/integration/src/setup.rs
Labels: runtime

#1137 dApp Staking v3 - Fix for Incorrect (Incomplete) Expired Entry Cleanup
  pallets/dapp-staking-v3/src/benchmarking/mod.rs
  pallets/dapp-staking-v3/src/benchmarking/utils.rs
  pallets/dapp-staking-v3/src/lib.rs
  pallets/dapp-staking-v3/src/migrations.rs
  pallets/dapp-staking-v3/src/test/testing_utils.rs
  pallets/dapp-staking-v3/src/test/tests_types.rs
  pallets/dapp-staking-v3/src/types.rs
  runtime/shibuya/src/lib.rs
Labels: runtime

#1139 Release v5.29.0 prep
  Cargo.lock
  bin/collator/Cargo.toml
  pallets/dapp-staking-v3/src/weights.rs
  runtime/astar/Cargo.toml
  runtime/astar/src/lib.rs
  runtime/local/Cargo.toml
  runtime/shibuya/Cargo.toml
  runtime/shibuya/src/lib.rs
  runtime/shibuya/src/weights/mod.rs
  runtime/shibuya/src/weights/pallet_dapp_staking_migration.rs
  runtime/shibuya/src/weights/pallet_dapp_staking_v3.rs
  runtime/shiden/Cargo.toml
  runtime/shiden/src/lib.rs
Labels: shibuya, runtime

#1140 fix: `BuyExecution` xcm benchmark tests
  .github/workflows/coverage.yaml
  pallets/astar-xcm-benchmarks/src/generic/benchmarking.rs
  pallets/astar-xcm-benchmarks/src/mock.rs
Labels: runtime, tests

#1141 Use 22.04 LTS for Docker build
  third-party/docker/Dockerfile
Labels: ci, other

#1144 Inflation UT fix
  pallets/inflation/src/mock.rs
  pallets/inflation/src/tests.rs
Labels: runtime, tests

#1146 Pallet inflation safety additions
  pallets/inflation/src/lib.rs
Labels: runtime

#1151 dApp staking v3 - claim staker benchmark fix
  pallets/dapp-staking-v3/src/benchmarking/mod.rs
  pallets/dapp-staking-v3/src/benchmarking/utils.rs
  pallets/dapp-staking-v3/src/test/tests.rs
Labels: runtime

#1153 Integrated dApps improvement
  pallets/dapp-staking-v3/src/lib.rs
  pallets/dapp-staking-v3/src/migrations.rs
  pallets/dapp-staking-v3/src/test/testing_utils.rs
  pallets/dapp-staking-v3/src/test/tests.rs
  pallets/dapp-staking-v3/src/test/tests_types.rs
  pallets/dapp-staking-v3/src/types.rs
  pallets/inflation/src/lib.rs
  runtime/shibuya/src/lib.rs
Labels: shibuya, runtime

#1155 Relaxed decommission mode
  pallets/dapps-staking/src/pallet/mod.rs
  pallets/dapps-staking/src/tests.rs
Labels: runtime

#1156 Feat/delegated claim charging
  pallets/dapp-staking-migration/src/mock.rs
  pallets/dapps-staking/src/mock.rs
  pallets/dapps-staking/src/pallet/mod.rs
  pallets/dapps-staking/src/tests.rs
  precompiles/dapps-staking/src/mock.rs
  runtime/astar/src/lib.rs
  runtime/local/src/lib.rs
  runtime/shiden/src/lib.rs
  tests/xcm-simulator/src/mocks/parachain.rs
Labels: runtime

#1159 Release v5.30.0 prep
  Cargo.lock
  bin/collator/Cargo.toml
  runtime/astar/Cargo.toml
  runtime/astar/src/lib.rs
  runtime/local/Cargo.toml
  runtime/shibuya/Cargo.toml
  runtime/shibuya/src/lib.rs
  runtime/shiden/Cargo.toml
  runtime/shiden/src/lib.rs
Labels: runtime
