Repository AstarNetwork/Astar, pull requests merged in 2024-05, with the labels that each got.

#1231 Oracle Solution Integration - Astar&Shiden
  Cargo.lock
  bin/collator/src/parachain/chain_spec/astar.rs
  bin/collator/src/parachain/chain_spec/shiden.rs
  runtime/astar/Cargo.toml
  runtime/astar/src/lib.rs
  runtime/shibuya/Cargo.toml
  runtime/shibuya/src/lib.rs
  runtime/shiden/Cargo.toml
  runtime/shiden/src/lib.rs
  tests/integration/src/lib.rs
  tests/integration/src/setup.rs
Labels: shiden, astar, shibuya, runtime

#1230 Tier config recalculation at the start of each era
  pallets/dapp-staking-v3/src/benchmarking/mod.rs
  pallets/dapp-staking-v3/src/benchmarking/utils.rs
  pallets/dapp-staking-v3/src/lib.rs
  pallets/dapp-staking-v3/src/test/mock.rs
  pallets/dapp-staking-v3/src/test/tests.rs
  runtime/astar/src/weights/pallet_dapp_staking_v3.rs
  runtime/shibuya/src/weights/pallet_dapp_staking_v3.rs
  runtime/shiden/src/weights/pallet_dapp_staking_v3.rs
Labels: runtime

#1233 fix export genesis state
  bin/collator/src/command.rs
Labels: client

#1235 remove genesis state print
  bin/collator/src/command.rs
Labels: client

#1237 cleanup command after last merge
  bin/collator/src/command.rs
Labels: other

#1239 v5.38.0 release prep
  Cargo.lock
  bin/collator/Cargo.toml
  runtime/astar/Cargo.toml
  runtime/astar/src/lib.rs
  runtime/local/Cargo.toml
  runtime/shibuya/Cargo.toml
  runtime/shibuya/src/lib.rs
  runtime/shiden/Cargo.toml
  runtime/shiden/src/lib.rs
Labels: other

#1244 burn extrinsic integration
  Cargo.lock
  Cargo.toml
  runtime/local/src/weights/pallet_balances.rs
  runtime/shibuya/src/weights/pallet_balances.rs
Labels: shiden, astar, shibuya, runtime

#1242 fix shiden genesis sync
  bin/collator/src/local/service.rs
  bin/collator/src/parachain/mod.rs
  bin/collator/src/parachain/service.rs
  bin/collator/src/parachain/shell_upgrade.rs
  bin/collator/src/rpc.rs
Labels: shiden, client

#1243 update tests to use cargo-nextest if present
  .github/workflows/release.yml
  .github/workflows/tests.yaml
  Makefile
Labels: ci, tests

#1246 Prep for v5.39.0 release
  Cargo.lock
  bin/collator/Cargo.toml
  runtime/astar/Cargo.toml
  runtime/astar/src/lib.rs
  runtime/local/Cargo.toml
  runtime/shibuya/Cargo.toml
  runtime/shibuya/src/lib.rs
  runtime/shiden/Cargo.toml
  runtime/shiden/src/lib.rs
Labels: shiden, shibuya, other

#1247 gh action to run e2e tests
  .github/workflows/e2e-tests.yaml
Labels: ci

#1251 update gh-e2e-tests build cmd
  .github/workflows/e2e-tests.yaml
Labels: ci

#1252 Base native currency price for dApp Staking
  Cargo.lock
  bin/collator/Cargo.toml
  pallets/dapp-staking-v3/src/benchmarking/utils.rs
  pallets/dapp-staking-v3/src/lib.rs
  pallets/dapp-staking-v3/src/test/mock.rs
  pallets/dapp-staking-v3/src/test/tests.rs
  pallets/dapp-staking-v3/src/test/tests_types.rs
  pallets/dapp-staking-v3/src/types.rs
  precompiles/dapp-staking-v3/src/test/mock.rs
  runtime/astar/Cargo.toml
  runtime/astar/src/lib.rs
  runtime/local/Cargo.toml
  runtime/local/src/lib.rs
  runtime/shibuya/Cargo.toml
  runtime/shibuya/src/lib.rs
  runtime/shiden/Cargo.toml
  runtime/shiden/src/lib.rs
  tests/xcm-simulator/src/mocks/parachain.rs
Labels: shiden, astar, shibuya, runtime
