Repository AstarNetwork/Astar, pull requests merged in 2024-06, with the labels that each got.

#1249 Frontier RPC tests
  .github/workflows/frontier-rpc-tests.yml
  Cargo.lock
  Cargo.toml
  bin/collator/Cargo.toml
  bin/collator/src/local/service.rs
  bin/collator/src/parachain/service.rs
  bin/collator/src/rpc.rs
Labels: ci

#1254 gha check migrations
  .github/workflows/check-migrations.yml
Labels: ci

#1255 remove legacy zombienet tests
  .github/workflows/release.yml
  .github/workflows/zombienetRpcTest.yml
  rpc-tests/.gitignore
  rpc-tests/README.md
  rpc-tests/claim.mjs
  rpc-tests/js-script_readme.md
  rpc-tests/package.json
  rpc-tests/rpc-tests.toml
  rpc-tests/rpc-tests.zndsl
  rpc-tests/tests/0001-balance-xcm-asset.js
  rpc-tests/tests/0001-custom.sh
  rpc-tests/tests/0001-dappsttaking-bondandstake.js
  rpc-tests/tests/0001-fetch-name-and-chain-from-rpc-node.js
  rpc-tests/tests/0001-parse-block.js
  rpc-tests/tests/0001-register-contract-on-h160.js
  rpc-tests/tests/0001-register-xcasset.js
  rpc-tests/tests/0001-transfer-reserve-asset-to-sibling.js
  rpc-tests/tests/0001-transfer-tokens-to-evm-mapped-account.js
  rpc-tests/tests/0001-transfer-tokens.js
  rpc-tests/tests/0002-deploy-an-evm-contract.js
  rpc-tests/tests/0002-get-evm-contract-data.js
  rpc-tests/tests/0002-set-evm-contract-data.js
  rpc-tests/tests/compile.mjs
  rpc-tests/tests/tx-utils.mjs
  rpc-tests/yarn.lock
Labels: ci, tests

#1258 Upd/shibuya specs
  bin/collator/res/shibuya.json
  bin/collator/res/shibuya.raw.json
Labels: shibuya, client

#1257 chain sync test
  .github/workflows/release.yml
  scripts/sync.sh
Labels: ci, tests

#1261 Update Tokyo to new chain (Paseo based)
  bin/collator/res/tokyo.json
  bin/collator/res/tokyo.raw.json
Labels: client

#1259 evm tracing test
  .github/workflows/frontier-rpc-tests.yml
  Cargo.lock
  bin/collator/src/evm_tracing_types.rs
  bin/collator/src/local/service.rs
  tests/integration/Cargo.toml
  tests/integration/src/evm_tracing.rs
  tests/integration/src/lib.rs
Labels: ci, tests

#1262 try-runtime clear prefix for large storage maps
  .github/try-runtime-storage.yml
  .github/workflows/check-migrations.yml
Labels: ci

#1240 stakingv3: rank dapps in-between tiers
  pallets/dapp-staking-v3/rpc/runtime-api/src/lib.rs
  pallets/dapp-staking-v3/src/benchmarking/mod.rs
  pallets/dapp-staking-v3/src/lib.rs
  pallets/dapp-staking-v3/src/migration.rs
  pallets/dapp-staking-v3/src/test/mock.rs
  pallets/dapp-staking-v3/src/test/testing_utils.rs
  pallets/dapp-staking-v3/src/test/tests.rs
  pallets/dapp-staking-v3/src/test/tests_types.rs
  pallets/dapp-staking-v3/src/types.rs
  precompiles/dapp-staking-v3/src/test/mock.rs
  primitives/src/dapp_staking.rs
  runtime/astar/src/lib.rs
  runtime/astar/src/weights/pallet_dapp_staking_v3.rs
  runtime/local/src/lib.rs
  runtime/shibuya/src/lib.rs
  runtime/shibuya/src/weights/pallet_dapp_staking_v3.rs
  runtime/shiden/src/lib.rs
  runtime/shiden/src/weights/pallet_dapp_staking_v3.rs
  tests/xcm-simulator/src/mocks/parachain.rs
Labels: enhancement, dapps-staking, runtime, other

#1263 client refactor
  Cargo.lock
  Cargo.toml
  bin/collator/Cargo.toml
  bin/collator/src/command.rs
  bin/collator/src/local/service.rs
  bin/collator/src/parachain/mod.rs
  bin/collator/src/parachain/service.rs
  bin/collator/src/parachain/shell_upgrade.rs
Labels: client

#1267 Patch publish ci
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  bin/collator/Cargo.toml
  bin/collator/src/command.rs
  bin/collator/src/local/service.rs
  bin/collator/src/parachain/mod.rs
  bin/collator/src/parachain/service.rs
  bin/collator/src/parachain/shell_upgrade.rs
Labels: ci

#1268 Undo "client refactor (#1263)" revert
  Cargo.lock
  Cargo.toml
  bin/collator/Cargo.toml
  bin/collator/src/command.rs
  bin/collator/src/local/service.rs
  bin/collator/src/parachain/mod.rs
  bin/collator/src/parachain/service.rs
  bin/collator/src/parachain/shell_upgrade.rs
Labels: client

#1269 fix upgrade e2e test
  tests/e2e/package.json
  tests/e2e/tests/runtime-upgrade.test.ts
  tests/e2e/vitest.config.mts
  tests/e2e/yarn.lock
Labels: ci, tests

#1271 fix console typo
  tests/e2e/tests/runtime-upgrade.test.ts
Labels: ci, tests

#1270 Fix staked amount too high after unstake issue
  pallets/dapp-staking-v3/src/test/testing_utils.rs
  pallets/dapp-staking-v3/src/test/tests.rs
  pallets/dapp-staking-v3/src/test/tests_types.rs
  pallets/dapp-staking-v3/src/types.rs
Labels: shiden, astar, shibuya, runtime

#1272 fix aura consensus fallback
  bin/collator/src/parachain/service.rs
Labels: client

#1273 v5.41.0 release prep
  Cargo.lock
  bin/collator/Cargo.toml
  runtime/astar/Cargo.toml
  runtime/astar/src/lib.rs
  runtime/shibuya/Cargo.toml
  runtime/shibuya/src/lib.rs
  runtime/shiden/Cargo.toml
  runtime/shiden/src/lib.rs
Labels: other

#1275 Fix incorrect check for locked/frozen amount
  pallets/dapp-staking-v3/src/lib.rs
  pallets/dapp-staking-v3/src/test/testing_utils.rs
  pallets/dapp-staking-v3/src/test/tests.rs
Labels: shiden, astar, shibuya, runtime

#1276 Fix account call for freeze/lock inconsistency
  pallets/dapp-staking-v3/src/lib.rs
  pallets/dapp-staking-v3/src/test/tests.rs
Labels: runtime

#1279 improve makefile
  Makefile
Labels: other

#1278 Zepter integration
  .config/zepter.yaml
  .github/workflows/zepter.yml
  bin/collator/Cargo.toml
  chain-extensions/pallet-assets/Cargo.toml
  chain-extensions/unified-accounts/Cargo.toml
  chain-extensions/xvm/Cargo.toml
  pallets/astar-xcm-benchmarks/Cargo.toml
  pallets/collator-selection/Cargo.toml
  pallets/dapp-staking-migration/Cargo.toml
  pallets/dapp-staking-v3/Cargo.toml
  pallets/dynamic-evm-base-fee/Cargo.toml
  pallets/ethereum-checked/Cargo.toml
  pallets/inflation/Cargo.toml
  pallets/oracle-benchmarks/Cargo.toml
  pallets/price-aggregator/Cargo.toml
  pallets/static-price-provider/Cargo.toml
  pallets/unified-accounts/Cargo.toml
  pallets/xc-asset-config/Cargo.toml
  pallets/xvm/Cargo.toml
  precompiles/assets-erc20/Cargo.toml
  precompiles/dapp-staking-v3/Cargo.toml
  precompiles/dispatch-lockdrop/Cargo.toml
  precompiles/sr25519/Cargo.toml
  precompiles/substrate-ecdsa/Cargo.toml
  precompiles/unified-accounts/Cargo.toml
  precompiles/utils/Cargo.toml
  precompiles/utils/macro/Cargo.toml
  precompiles/xcm/Cargo.toml
  precompiles/xvm/Cargo.toml
  primitives/Cargo.toml
  runtime/astar/Cargo.toml
  runtime/local/Cargo.toml
  runtime/shibuya/Cargo.toml
  runtime/shiden/Cargo.toml
  rust-toolchain.toml
  tests/integration/Cargo.toml
  tests/utils/Cargo.toml
  vendor/primitives/debug/Cargo.toml
  vendor/runtime/evm-tracer/Cargo.toml
Labels: ci

#1280 revert node id
  bin/collator/res/shibuya.json
  bin/collator/res/shibuya.raw.json
Labels: bug, shibuya, client

#1282 zombienet smoke test
  .devcontainer/devcontainer.json
  .github/workflows/release.yml
  scripts/sync-smoke.sh
  third-party/zombienet/setup.sh
  third-party/zombienet/smoke.toml
  third-party/zombienet/smoke.zndsl
Labels: ci, tests

#1284 CI: update clippy
  .github/workflows/static-analysis.yml
Labels: ci
