Repository AstarNetwork/Astar, pull requests merged in 2024-09, with the labels that each got.

#1348 Remove unused extrinsic from dapp staking
  pallets/dapp-staking/src/lib.rs
  pallets/dapp-staking/src/test/tests.rs
  pallets/dapp-staking/src/types.rs
Labels: runtime

#1353 prep v5.44.0
  Cargo.lock
  bin/collator/Cargo.toml
  bin/collator/res/shibuya.raw.json
  runtime/astar/Cargo.toml
  runtime/astar/src/lib.rs
  runtime/local/Cargo.toml
  runtime/shibuya/Cargo.toml
  runtime/shibuya/src/lib.rs
  runtime/shiden/Cargo.toml
  runtime/shiden/src/lib.rs
Labels: shibuya, client

#1354 fix build (optimised) gha
  .github/workflows/release.yml
Labels: ci

#1351 Modify Shibuya governance params
  primitives/src/governance.rs
  runtime/shibuya/src/lib.rs
Labels: shibuya, runtime

#1355 MacOs CI disk cleanup
  .github/workflows/release.yml
Labels: ci, other

#1352 Separate client/runtime release
  .github/scripts/generate-release-body.ts
  .github/workflows/base_checks.yaml
  .github/workflows/release-client.yml
  .github/workflows/release-runtime.yml
  .github/workflows/tests.yaml
  README.md
Labels: ci, other

#1361 Bump CI upload/download actions (fix tarpaulin job)
  .github/workflows/benchmark.yml
  .github/workflows/coverage.yaml
  .github/workflows/release-client.yml
  .github/workflows/release-runtime.yml
Labels: ci, other

#1363 Fix revert command when running as parachain
  bin/collator/src/command.rs
Labels: parachain, astar, client
