Repository AstarNetwork/Astar, pull requests merged in 2025-07, with the labels that each got.

#1498 TryState checks workflow
  .github/workflows/check-try-state.yml
Labels: ci

#1500 Allow tech comm & council to trigger maintenance
  primitives/src/governance.rs
  runtime/astar/src/lib.rs
Labels: runtime

#1499 TryState checks workflow run on production runtimes
  .github/workflows/check-try-state.yml
Labels: ci

#1502 feat: add extrisinc to add/remove single invulnerables
  pallets/collator-selection/src/benchmarking.rs
  pallets/collator-selection/src/lib.rs
  pallets/collator-selection/src/tests.rs
  pallets/collator-selection/src/weights.rs
Labels: runtime

#1506 Minor release runtime optimization
  .github/workflows/release-runtime.yml
Labels: ci

#1319 Frame Omni Bencher integration
  .github/workflows/README.md
  .github/workflows/benchmark.yml
  scripts/run_benchmarks.sh
Labels: ci, other, project

#1512 Omni-bencher installation fix
  .github/workflows/benchmark.yml
Labels: ci

#1513 Omni bencher fix try5
  .github/workflows/benchmark.yml
Labels: ci

#1504 Update XCM test
  precompiles/xcm/src/tests.rs
Labels: tests

#1522 Zepter fix
  .github/workflows/zepter.yml
Labels: ci

#1501 TxPause&SafeMode for Astar
  Cargo.lock
  runtime/astar/Cargo.toml
  runtime/astar/src/genesis_config.rs
  runtime/astar/src/lib.rs
  runtime/astar/src/weights/block_weights.rs
  runtime/astar/src/weights/extrinsic_weights.rs
  runtime/shibuya/src/lib.rs
  scripts/run_benchmarks.sh
  tests/integration/Cargo.toml
  tests/integration/src/governance.rs
Labels: runtime

#1524 Runtime-1700 prep
  Cargo.lock
  runtime/astar/Cargo.toml
  runtime/astar/src/lib.rs
  runtime/shibuya/Cargo.toml
  runtime/shibuya/src/lib.rs
  runtime/shiden/Cargo.toml
  runtime/shiden/src/lib.rs
Labels: runtime
